services:
  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/code/app
  client:
    build: client
    ports:
      - "8080:5173"
    volumes:
      - ./client/src:/app/src
