services:
  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/code/app
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES}
      - LOCAL_IP_ADDRESS=${LOCAL_IP_ADDRESS}
    depends_on:
      - redis
  client:
    build: client
    ports:
      - "8080:5173"
    volumes:
      - ./client/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - VITE_SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - VITE_LOCAL_IP_ADDRESS=${LOCAL_IP_ADDRESS}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"