services:
  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/code/app
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
  client:
    build: client
    ports:
      - "8080:5173"
    volumes:
      - ./client/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - VITE_SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}